### PR TITLE
Quantity is 12 decimal places in my case - Fix

### LINKED ISSUE #25: Quantity precision is 12 in my case 😱
- Quantity precision is 12 in my case 😱

### PR DESCRIPTION
**Pull request by gabrielbmoro**
Closes https://github.com/theolm/ambush-app/issues/25

### CODE REVIEW

File: lib/src/domain/models/invoice.dart [hunk 1]
```diff
@@ -25,4 +25,17 @@ class Invoice {
     this.createdAt,
     this.updatedAt,
   );
+
```
Comment (gabrielbmoro) [inline lib/src/domain/models/invoice.dart:28]: I moved the logic to convert the currency values to text to be part of the invoice obj.

**Review by theolm — APPROVED** [review]
